version: "3.7"
services:
  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: lowes-url-shortener
    restart: on-failure
    depends_on:
      - mysql_db
    ports:
      - 8080:8080
    links:
      - mysql_db:app_db
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
