version: '3'

services:

  mysql-local:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - /data/mysql
    networks:
      - "my-network"
  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: lowes-urlshortener
    restart: on-failure
    depends_on:
      - mysql-local
    ports:
      - 8080:8080
    volumes:
      - /data/myapp
    networks:
      - "my-network"
  networks:
    my-network:
